<a href="https://colab.research.google.com/github/Anjali8499/Python-libraries/blob/main/Day1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy


In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)  ###1-d array

[1 2 3]


In [3]:
a.shape

(3,)

In [4]:
a.ndim  ###get the dimension

1

In [5]:
a.size  ##total number of elements

3

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
type(a)

numpy.ndarray

In [9]:
b=np.array([[2,3,4],[4,5,6]])
print(b)  ### 2-d array

[[2 3 4]
 [4 5 6]]


In [10]:
b.shape  ##(rows, columns)

(2, 3)

In [11]:
b.ndim

2

In [12]:
b.dtype  #### int32= 4 bytes (1byte=8bits)

dtype('int64')

In [13]:
b=np.array([[2,3,4],[4,5,6]], dtype="int16")
print(b)  ### 2-d array

[[2 3 4]
 [4 5 6]]


In [14]:
b.dtype

dtype('int16')

In [15]:
b.size

6

In [16]:
b.itemsize  ###equiv no. of bytes 

2

#### Access/change specific rows and columns  [row,column], startindex:endindex

In [17]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)   

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a[0,1:6:2]    ####Important!!! ####Important!!! ####Important!!! ####Important!!!

array([2, 4, 6])

In [19]:
a[0,1:-1:2]

array([2, 4, 6])

In [20]:
a[0,3]

4

In [21]:
a.shape

(2, 7)

In [22]:
a[0,5]

6

In [23]:
a[:,2]

array([ 3, 10])

In [24]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
a[1,5]=22

In [26]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 22, 14]])

In [27]:
a[:,2]=5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 22, 14]])

In [28]:
a[:,2]=9,10
a

array([[ 1,  2,  9,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 22, 14]])

## Initializing different types of array

In [29]:
## All zeros matrix

np.zeros(5) ## vector 

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((2,3))  ## 2-d matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
## All ones matrix

np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.full((3,3,2), 109)

array([[[109, 109],
        [109, 109],
        [109, 109]],

       [[109, 109],
        [109, 109],
        [109, 109]],

       [[109, 109],
        [109, 109],
        [109, 109]]])

In [34]:
c = np.full_like(a,6)
print(c)

[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]]


In [35]:
c.shape

(2, 7)

In [36]:
c.reshape(7,2)

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

In [37]:
### Initialize a matrix of random numbers

np.random.rand(4,3)   ####Important!!!

array([[0.704546  , 0.04458974, 0.28865042],
       [0.0415202 , 0.30679753, 0.52823281],
       [0.04335431, 0.44796857, 0.46613353],
       [0.28297097, 0.98376351, 0.78022548]])

In [38]:
np.random.random_sample(a.shape)

array([[0.17972053, 0.68871649, 0.75756186, 0.33037007, 0.46529726,
        0.48504149, 0.07505444],
       [0.54842572, 0.39764647, 0.12588864, 0.68042499, 0.54504713,
        0.04863319, 0.03169177]])

In [39]:
### Random integer values

np.random.randint(6, size=(3,3))   ####Important!!!

array([[1, 1, 1],
       [3, 5, 3],
       [0, 3, 2]])

In [40]:
np.random.randint(-8,8, size=(4,3))

array([[-5, -6,  7],
       [-1,  6,  0],
       [ 2, -3, -3],
       [ 6,  7, -1]])

In [41]:
## Identity matrix

In [42]:
np.identity(3)  ### square matrix    ####Important!!!

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.identity(5)  ### square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
### repeat an array

In [45]:
arr=np.array([[1,2,3]])
arr1=np.repeat(arr,3, axis=0)
print(arr1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
a=np.array([1,2,3])
b=a
b

array([1, 2, 3])

In [47]:
b[0]=900
b

array([900,   2,   3])

In [48]:
a

array([900,   2,   3])

In [49]:
a=np.array([1,2,3])
b=a.copy()
b[0]=900
b

array([900,   2,   3])

In [50]:
a

array([1, 2, 3])

In [51]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [52]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [53]:
a

array([1, 2, 3, 4])

In [54]:
a+=2
a

array([3, 4, 5, 6])

In [55]:
b=np.array([3,0,4,0])

In [56]:
a+b

array([6, 4, 9, 6])

In [57]:
a**b

array([ 27,   1, 625,   1])

In [58]:
a

array([3, 4, 5, 6])

In [59]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [60]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [61]:
##Linear algebra using np